# Generated by Django 5.2.7 on 2025-11-01 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('.py', 'Python')], max_length=10)),
                ('extract_file_path', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_folder_path', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_zip_path', models.CharField(blank=True, max_length=100, null=True)),
                ('used_coin', models.IntegerField(default=1)),
                ('is_finished', models.BooleanField(default=False)),
                ('slug', models.CharField(blank=True, max_length=30)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoinTransAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCREMENT', 'INCREMENT'), ('DECREMENT', 'DECREMENT')], max_length=20)),
                ('used_coin', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=200, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('for_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectmodel')),
            ],
        ),
    ]
